badges and timer
nBobrov/TestGuru pull request #23
Opened 2021-10-26 07:26 UTC by nBobrov

badges and timer

2021-10-26 19:49 UTC, BubuntuClu requested changes

2021-10-26 19:49 UTC, BubuntuClu commented on app/controllers/badges_controller.rb
> +    @badges = Badge.with_user(current_user.id)
`current_user.badges`

2021-10-26 19:49 UTC, BubuntuClu commented on app/services/badge_rules/all_tests_from_category_specification.rb
> +    Test.where(category: category)
у тебя есть метод поиска тестов по названию категории. используй его

2021-10-26 19:49 UTC, BubuntuClu commented on app/services/badge_assign_service.rb
> +      assign_badge(badge) if rule.satisfies?
`user.badges << badge if rule.satisfies?`

2021-10-26 19:49 UTC, BubuntuClu commented on app/services/badge_assign_service.rb
> +      rule = RULES[badge.rule_type.to_sym].new(rule_value: badge.rule_value, test_passage: @test_passage)
мне каажется, правило надо из бейджа доставать. чтобы у тебя все настройки были в одном месте, а не разбросаны по разным файлам.

можно вообще в правило записать имя класса, который надо инстанцировать, тогда не будет этого хэша

2021-10-29 00:16 UTC, merged

2021-11-01 00:39 UTC, nBobrov commented on app/controllers/badges_controller.rb
> +    @badges = Badge.with_user(current_user.id)
Тут возвращается список всех бейджей и user_id, если бейдж был им получен. Для выполнения следующего требования: Пользователь в любой момент времени может посмотреть список всех существующих и заработанных бэйджей.

current_user.badges вернет только заработанные пользователем бейджи

2021-11-01 07:42 UTC, BubuntuClu commented on app/controllers/badges_controller.rb
> +    @badges = Badge.with_user(current_user.id)
ну, один список `current_user.badges` а второй `Badge.all`